services:
  postgres:
    image: postgres:16
    container_name: sisf-postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  xgb-api:
    build:
      context: ./predictor
    container_name: xgb-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

volumes:
  postgres_data:
