[platformio]
extra_configs = secrets.ini
src_dir = firmware

[env:esp32doit-devkit-v1]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_type = debug
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
upload_resetmethod = nodemcu
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, default

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8

build_flags =
    -D MQTT_HOST=\"4b5d99a20d0b4b0f92983d07a06528fb.s1.eu.hivemq.cloud\"
    -D MQTT_PORT=8883
    -D MQTT_TOPIC=\"sisf/sensor/data\"
    ${secrets.build_flags}