[platformio]
extra_configs = secrets.ini
src_dir = firmware

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8

build_flags =
    -D MQTT_HOST=\"mosquitto\"     
    -D MQTT_PORT=8883
    -D MQTT_TOPIC=\"sensor/data\"
    ${secrets.build_flags}