export const lang = {
  EN: {
    dashboard: "SISF Dashboard",
    settings: "Settings",
    device: "Device",
    temperature: "Temperature",
    humidity: "Humidity",
    currentTemp: "Current Temperature",
    currentHum: "Current Humidity",
    monitoring: "Monitoring",
    display: "Display",
    deviceName: "Device Name",
    deviceId: "Device ID",
    interval: "Interval",
    language: "Language",
    tempUnit: "Temperature Unit",
  },

  ID: {
    dashboard: "SISF Dashboard",
    settings: "Pengaturan",
    device: "Perangkat",
    temperature: "Suhu",
    humidity: "Kelembapan",
    currentTemp: "Suhu Saat Ini",
    currentHum: "Kelembapan Saat Ini",
    monitoring: "Pemantauan",
    display: "Tampilan",
    deviceName: "Nama Perangkat",
    deviceId: "ID Perangkat",
    interval: "Interval",
    language: "Bahasa",
    tempUnit: "Satuan Suhu",
  },
};