export const lang = {
  EN: {
    dashboard: "SISF Dashboard",
    settings: "Settings",
    device: "Device",
    temperature: "Temperature",
    humidity: "Humidity",
    currentTemp: "Current Temperature",
    currentHum: "Current Humidity",
    latestTemp: "Latest Temperature",
    latestHum: "Latest Humidity",
    monitoring: "Monitoring",
    display: "Display",
    deviceName: "Device Name",
    deviceId: "Device ID",
    interval: "Interval",
    language: "Language",
    tempUnit: "Temperature Unit",
    low: "LOW",
    normal: "NORMAL",
    warning: "HIGH",
    danger: "VERY HIGH",
    actualTemp: "Actual Temperature",
    actualHum: "Actual Humidity",
    predictedTemp: "Predicted Temperature",
    predictedHum: "Predicted Humidity",
  },

  ID: {
    dashboard: "SISF Dashboard",
    settings: "Pengaturan",
    device: "Perangkat",
    temperature: "Suhu",
    humidity: "Kelembapan",
    currentTemp: "Suhu Saat Ini",
    currentHum: "Kelembapan Saat Ini",
    latestTemp: "Suhu Terbaru",
    latestHum: "Kelembapan Terbaru",
    monitoring: "Pemantauan",
    display: "Tampilan",
    deviceName: "Nama Perangkat",
    deviceId: "ID Perangkat",
    interval: "Interval",
    language: "Bahasa",
    tempUnit: "Satuan Suhu",
    low: "RENDAH",
    normal: "NORMAL",
    warning: "TINGGI",
    danger: "SANGAT TINGGI",
    actualTemp: "Suhu Aktual",
    actualHum: "Kelembapan Aktual",
    predictedTemp: "Prediksi Suhu",
    predictedHum: "Prediksi Kelembapan",
  },
};